namespace QuickUnity.Config
{
    /// <summary>
    /// TestData
	/// Note: Generated by Editor automatically. Please don't edit this file manually !
    /// </summary>
    public sealed class TestData : ConfigMetadata
    {
		/// <summary>
		/// ID
		/// </summary>
		public int id;

		/// <summary>
		/// 名称
		/// </summary>
		public string name;

		/// <summary>
		/// 数值
		/// </summary>
		public float value;
    }
}