using QuickUnity.Config;

namespace QuickUnity.Examples.Config.VO
{
    /// <summary>
    /// TestData
	/// Note: Generated by Editor automatically. Please don't edit this file manually !
    /// </summary>
    public sealed class TestData : ConfigMetadata
    {
		/// <summary>
		/// ID
		/// </summary>
		public long id;

		/// <summary>
		/// 测试布尔
		/// test bool
		/// </summary>
		public bool testBool;

		/// <summary>
		/// test byte
		/// </summary>
		public byte testByte;

		/// <summary>
		/// test sbyte
		/// </summary>
		public sbyte testSByte;

		/// <summary>
		/// test short
		/// </summary>
		public short testShort;

		/// <summary>
		/// test ushort
		/// </summary>
		public ushort testUShort;

		/// <summary>
		/// test int
		/// </summary>
		public int testInt;

		/// <summary>
		/// test uint
		/// </summary>
		public uint testUInt;

		/// <summary>
		/// test ulong
		/// </summary>
		public ulong testULong;

		/// <summary>
		/// test float
		/// </summary>
		public float testFloat;

		/// <summary>
		/// test double
		/// </summary>
		public double testDouble;

		/// <summary>
		/// test decimal
		/// </summary>
		public decimal testDecimal;

		/// <summary>
		/// test string
		/// </summary>
		public string testString;

		/// <summary>
        /// Initializes a new instance of the <see cref="TestData"/> class.
        /// </summary>
        public TestData()
        {
        }
    }
}