using QuickUnity.Config;

namespace QuickUnity.Config.VO
{
    /// <summary>
    /// TestData
	/// Note: Generated by Editor automatically. Please don't edit this file manually !
    /// </summary>
    public sealed class TestData : ConfigMetadata
    {
		/// <summary>
		/// ID
		/// </summary>
		public long id;

		/// <summary>
		/// 名称
		/// </summary>
		public string name;

		/// <summary>
		/// 数值
		/// </summary>
		public float value;

		/// <summary>
        /// Initializes a new instance of the <see cref="TestData"/> class.
        /// </summary>
        public TestData()
        {
        }
    }
}